// This page exists to serve the sitemap at the root level
// The actual sitemap XML is generated by the API route at /api/sitemap.xml

export async function generateMetadata() {
  return {
    robots: {
      index: false, // Prevent indexing of this page since it's just a redirect to the XML sitemap
    },
  };
}

export default function SitemapPage() {
  // This page intentionally left blank
  // The sitemap is served as XML from the /api/sitemap.xml route
  return null;
}